// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZxSPMWgkLtghJAEf-Fn_NMMVox6QUR4',
    appId: '1:533489489121:web:9b2ae102923e646eced3a0',
    messagingSenderId: '533489489121',
    projectId: 'mathereye',
    authDomain: 'mathereye.firebaseapp.com',
    storageBucket: 'mathereye.firebasestorage.app',
    measurementId: 'G-9FHC2PGKEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeRE8B36hRW6VT8w8q1zph1ChVRcBEqB4',
    appId: '1:533489489121:android:43dc4b2d0dbdc947ced3a0',
    messagingSenderId: '533489489121',
    projectId: 'mathereye',
    storageBucket: 'mathereye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzM04TVdUvwVlT3JBHr_zdqABLtUd5sCc',
    appId: '1:533489489121:ios:eabe68453656c6a3ced3a0',
    messagingSenderId: '533489489121',
    projectId: 'mathereye',
    storageBucket: 'mathereye.firebasestorage.app',
    iosBundleId: 'com.mothereye.mothereye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzM04TVdUvwVlT3JBHr_zdqABLtUd5sCc',
    appId: '1:533489489121:ios:eabe68453656c6a3ced3a0',
    messagingSenderId: '533489489121',
    projectId: 'mathereye',
    storageBucket: 'mathereye.firebasestorage.app',
    iosBundleId: 'com.mothereye.mothereye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ZxSPMWgkLtghJAEf-Fn_NMMVox6QUR4',
    appId: '1:533489489121:web:885ff1100b3707b3ced3a0',
    messagingSenderId: '533489489121',
    projectId: 'mathereye',
    authDomain: 'mathereye.firebaseapp.com',
    storageBucket: 'mathereye.firebasestorage.app',
    measurementId: 'G-RC7VR62T6N',
  );
}
